fix CI

diff --git a/.github/workflows/build-artifact.yml b/.github/workflows/build-artifact.yml
--- a/.github/workflows/build-artifact.yml
+++ b/.github/workflows/build-artifact.yml
@@ -65,12 +65,12 @@ jobs:
       - name: Determine Version
         shell: pwsh
         run: |
-          $text = [System.IO.File]::ReadAllText("OverlayPlugin\Properties\AssemblyInfo.cs");
-          $regex = [regex]::New('\[assembly: AssemblyVersion\("([0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+"\)');
+          $text = [System.IO.File]::ReadAllText("OverlayPlugin\OverlayPlugin.csproj");
+          $regex = [regex]::New('<AssemblyVersion>([0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+<\/AssemblyVersion>');
           $m = $regex.Match($text);
           if (-not $m) {
-              echo "Error: Version number not found in the AssemblyInfo.cs!"
-              exit 1
+            echo "Error: Version number not found in OverlayPlugin.csproj!"
+            exit 1
           }
           $version = $m.Groups[1]
           echo "version=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
